# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('clase', models.CharField(blank=True, default='my location default', max_length=120, null=True)),
                ('hora', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
