# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='clase',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
