# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0002_auto_20170522_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=False),
        ),
    ]
