# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0003_asistencia_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=True),
        ),
    ]
