# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0004_auto_20170527_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
