# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lista', '0005_auto_20170529_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
